FROM node:22-alpine AS builder

WORKDIR /app

COPY app-base/package*.json ./
RUN npm install

COPY app-base ./

RUN npm run build

FROM nginx:stable-alpine

COPY app-base/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]